### ISSUE TITLE
Is it possible to set poewrline frequency?

### ISSUE THREAD

**Issue by Alvazz** [zyxeeker/CameraTool_Qt#1]
Can this library set the camera's poewrline frequency?

**Comment by zyxeeker** [comment]
of course,
u can find it in this code
https://chromium.googlesource.com/chromium/src/media/+/refs/heads/main/capture/video/win/video_capture_device_win.cc#917

**Comment by Alvazz** [comment]
It seems that your project does not have this function, can you add it? thanks

**Comment by zyxeeker** [comment]
sure, i will update it in several days

**Comment by zyxeeker** [comment]
@Alvazz i update it, u can find it in [here](https://github.com/zyxeeker/CameraTool_Qt/blob/main/service/UVC_dshow.cpp#L178)

**Comment by Alvazz** [comment]
Thanks sir!

**Comment by Alvazz** [comment]
but, I got some error, how to fix it?

![error](https://user-images.githubusercontent.com/50744096/161000249-b2fb2a3f-6d5f-4d19-9f43-3e5987b10e24.png)

**Comment by Alvazz** [comment]
my app only can use "Use Unicode Character Set".  so how can I do? thanks!

**Comment by Alvazz** [comment]
OK, I fixed it.

But I found one other problem, this problem may lead to more serious error.
E.g:
```
bool UVCCameraLibrary::ConnectDevice(char *deviceName) {
    _GetEnumMoniker();

    if (m_EnumMoniker == nullptr)
        return false;

    int nDevices = 0;
    while (m_EnumMoniker->Next(1, &m_Moniker, &m_Fetched) == S_OK) {
        char cameraRealNames[256][256];

        IPropertyBag *pPropertyBag;
        TCHAR devname[256];
        m_Moniker->BindToStorage(0, 0, IID_IPropertyBag,
                                 (void **) &pPropertyBag);
        VARIANT var;
        var.vt = VT_BSTR;
        pPropertyBag->Read(L"FriendlyName", &var, 0);
        WideCharToMultiByte(CP_ACP, 0,
                            var.bstrVal, -1, devname, sizeof(devname), 0, 0);
        VariantClear(&var);

        int nSameNamedDevices = 0;
        for (int j = 0; j < nDevices; j++) {
            if (strcmp(cameraRealNames[j], devname) == 0)
                nSameNamedDevices++;
        }
        strcpy_s(cameraRealNames[nDevices], devname);

        if (nSameNamedDevices > 0)
            LOG::logger(LOG::LogLevel::INFO, "Camera name:" + std::string(devname));
        if (strcmp(devname, deviceName) == 0) {
            m_Moniker->BindToObject(0, 0, IID_IBaseFilter,
                                    (void **) &m_DeviceFilter);
            if (m_DeviceFilter != nullptr)
                return true;
        }

        // release
        m_Moniker->Release();
        pPropertyBag->Release();

        nDevices++;
    }
    return false;
}
```

This code uses the camera's deviceName as the Bind, but in some cases the name of the two cameras will be the same. For example, the names of the two cameras are called "USB Live Camera", so there is a possibility of duplication, in this case, there will be a bug

**Comment by zyxeeker** [comment]
u can get device`s CLSID, FriendlyName and DevicePath by this way
```
pPropertyBag->Read(L"CLSID", &var, 0);
pPropertyBag->Read(L"DevicePath ", &var, 0);
```
and u can find sample in [here](https://github.com/zyxeeker/CameraTool_Qt/blob/main/service/UVC_dshow.cpp#L106)

**Comment by Alvazz** [comment]
Thanks! and how can i get the status of the CheckBox, i mean say Auto status.

**Comment by zyxeeker** [comment]
This [code](https://github.com/zyxeeker/CameraTool_Qt/blob/main/mainwindow.cpp#L171) will show u how to watch QRadioButton`s status and do other things
u can compare [QAbstractButton](https://doc.qt.io/qt-5.15/qabstractbutton.html#toggled) with [QCheckbox](https://doc.qt.io/qt-5.15/qcheckbox.html#stateChanged) to change it
